layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.166628
  lightness: 0.3528464
  rhythmicContrast: 1
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.8802363
name: 'THEREALHARVEYKEITEL '
